defaults: &defaults
  machine:
  working_directory: ~/iot-data-model

version: 2.1
commands:

jobs:
  create-tags:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: create-tags
          command: |
            git config --global user.email "circleci@infarm.com"
            git config --global user.name "circle-ci"
            make create-tags

workflows:
  test-tagging:
    jobs:
      - create-tag:
          filters:
            branches:
              only: 
                - develop
                - master

