defaults: &defaults
  docker:
    - image: circleci/golang:1.15

version: 2.1
commands:

jobs:
  create-tags:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: create-tags
          command: |
            git config --global user.email "circleci@infarm.com"
            git config --global user.name "circle-ci"
            make create-tags

workflows:
  test-tagging:
    jobs:
      - create-tags:
          filters:
            branches:
              only: 
                - develop
                - staging
                - master

